import os, traceback

def return_canvas_schema_table_sql(table_name=""):

  sql_string = None

  if (table_name == "assignment_fact"):
    sql_string = "CREATE TABLE assignment_fact" + "\n" 
    sql_string += " (" + "\n"
    sql_string += " assignment_id bigint," + "\n"
    sql_string += " course_id bigint," + "\n"
    sql_string += " course_account_id bigint," + "\n"
    sql_string += " enrollment_term_id bigint," + "\n"
    sql_string += " points_possible double precision," + "\n"
    sql_string += " peer_review_count int," + "\n"
    sql_string += " assignment_group_id bigint" + "\n"
    sql_string += " );"

  if (table_name == "course_dim"):
    sql_string = "CREATE TABLE course_dim" + "\n" 
    sql_string += " (" + "\n"
    sql_string += " id bigint," + "\n"
    sql_string += " canvas_id bigint," + "\n"
    sql_string += " root_account_id bigint," + "\n"
    sql_string += " account_id  bigint," + "\n"
    sql_string += " enrollment_term_id  bigint," + "\n"
    sql_string += " name varchar," + "\n"
    sql_string += " code varchar," + "\n"
    sql_string += " type varchar," + "\n"
    sql_string += " created_at timestamp," + "\n"
    sql_string += " start_at timestamp," + "\n"
    sql_string += " conclude_at timestamp," + "\n"
    sql_string += " publicly_visible boolean," + "\n"
    sql_string += " sis_source_id varchar," + "\n"
    sql_string += " workflow_state varchar,"  + "\n"
    sql_string += " wiki_id bigint" + "\n" 
    sql_string += " );"

  elif (table_name == "enrollment_dim"):
    sql_string = "CREATE TABLE enrollment_dim" + "\n"
    sql_string += " (" + "\n"
    sql_string += " id bigint," + "\n"
    sql_string += " canvas_id bigint," + "\n"
    sql_string += " root_account_id bigint," + "\n"
    sql_string += " course_section_id bigint," + "\n"
    sql_string += " role_id bigint," + "\n"
    sql_string += " type  varchar," + "\n"
    sql_string += " workflow_state varchar," + "\n"
    sql_string += " created_at timestamp," + "\n"
    sql_string += " updated_at timestamp," + "\n"
    sql_string += " start_at timestamp," + "\n"
    sql_string += " end_at timestamp," + "\n"
    sql_string += " completed_at timestamp," + "\n"
    sql_string += " self_enrolled boolean," + "\n"
    sql_string += " sis_source_id varchar," + "\n"
    sql_string += " course_id bigint," + "\n"
    sql_string += " user_id bigint" + "\n"
    sql_string += " );"

  elif (table_name == "enrollment_term_dim"):
    sql_string = "CREATE TABLE enrollment_term_dim" + "\n" 
    sql_string += " (" + "\n"
    sql_string += " id bigint," + "\n"
    sql_string += " canvas_id bigint," + "\n"
    sql_string += " root_account_id bigint," + "\n"
    sql_string += " name varchar," + "\n"
    sql_string += " date_start timestamp," + "\n"
    sql_string += " date_end timestamp," + "\n"
    sql_string += " sis_source_id varchar" + "\n"
    sql_string += " );"

  elif (table_name == "requests"):
    sql_string = "CREATE TABLE requests" + "\n"
    sql_string += " (" + "\n"
    sql_string += " id uuid," + "\n"
    sql_string += " timestamp_utc timestamp," + "\n"
    sql_string += " timestamp_year varchar," + "\n"
    sql_string += " timestamp_month varchar," + "\n"
    sql_string += " timestamp_day varchar," + "\n"
    sql_string += " user_id bigint," + "\n"
    sql_string += " course_id bigint," + "\n"
    sql_string += " root_account_id bigint," + "\n"
    sql_string += " course_account_id bigint," + "\n"
    sql_string += " quiz_id bigint," + "\n"
    sql_string += " discussion_id bigint," + "\n"
    sql_string += " conversation_id bigint," + "\n"
    sql_string += " assignment_id bigint," + "\n"
    sql_string += " url text," + "\n"
    sql_string += " user_agent text," + "\n"
    sql_string += " http_method varchar," + "\n"
    sql_string += " remote_ip varchar," + "\n"
    sql_string += " interaction_micros bigint," + "\n"
    sql_string += " web_application_controller varchar," + "\n"
    sql_string += " web_applicaiton_action varchar," + "\n"
    sql_string += " web_application_context_type varchar," + "\n"
    sql_string += " web_application_context_id varchar," + "\n"
    sql_string += " real_user_id bigint," + "\n"
    sql_string += " session_id varchar," + "\n"
    sql_string += " user_agent_id bigint," + "\n"
    sql_string += " http_status varchar," + "\n"
    sql_string += " http_version varchar" + "\n"
    sql_string += " );"

  elif (table_name == "submission_fact"):

    sql_string = "CREATE TABLE submission_fact" + "\n"
    sql_string += " (" + "\n"
    sql_string += " submission_id bigint," + "\n"
    sql_string += " assignment_id bigint," + "\n"
    sql_string += " course_id bigint," + "\n"
    sql_string += " enrollment_term_id bigint," + "\n"
    sql_string += " user_id bigint," + "\n"
    sql_string += " grader_id bigint," + "\n"
    sql_string += " course_account_id bigint," + "\n"
    sql_string += " enrollment_rollup_id bigint," + "\n"
    sql_string += " score double precision," + "\n"
    sql_string += " published_score double precision," + "\n"
    sql_string += " what_if_score double precision," + "\n"
    sql_string += " submission_comments_count int," + "\n"
    sql_string += " account_id bigint," + "\n"
    sql_string += " assignment_group_id bigint," + "\n"
    sql_string += " group_id bigint," + "\n"
    sql_string += " quiz_id bigint," + "\n"
    sql_string += " quiz_submission_id bigint," + "\n"
    sql_string += " wiki_id bigint" + "\n"
    sql_string += " );"


  return(sql_string)
